name: ci

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        #os: [ubuntu-22.04, ubuntu-20.04, macos-13, macos-12, macos-11]
        #compiler: [ {cc: gcc, cxx: g++}, {cc: clang, cxx: clang++} ]
        include:
          - os: ubuntu-22.04
            compiler:
              cc: gcc
              cxx: g++
          - os: ubuntu-22.04
            compiler:
              cc: clang
              cxx: clang++
          - os: ubuntu-20.04
            compiler:
              cc: gcc
              cxx: g++
          - os: ubuntu-20.04
            compiler:
              cc: clang
              cxx: clang++
          - os: macos-13
            compiler:
              cc: clang
              cxx: clang++
          ##- os: macos-13
          ##  compiler:
          ##    cc: gcc
          ##    cxx: g++
          ####- os: macos-12
          ####  compiler:
          ####    cc: clang
          ####    cxx: clang++
          ####- os: macos-12
          ####  compiler:
          ####    cc: gcc
          ####    cxx: g++
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    ############################################################
    - name: prebuild
      shell: bash
      run: .build/github/prebuild -v -s ${{ matrix.os }} -c '${{runner.temp}}'/setup
    ############################################################
    - name: testing
      env:
        COMPILER_CC: ${{ matrix.compiler.cc }}
        COMPILER_CXX: ${{ matrix.compiler.cxx }}
      shell: bash
      run: .build/github/build -v -s ${{ matrix.os }} -c '${{runner.temp}}'/setup
    ############################################################
